vich_uploader:
    db_driver: orm

    mappings:
       products_images:
           uri_prefix: '%products_images%'
           upload_destination: '%kernel.project_dir%/public%products_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
